streams:
  - id: "stream0"
    uri: 'https://r1---sn-j5caxupj5-nwvl.googlevideo.com/videoplayback\?expire\=1629340931\&ei\=o3AdYeClA5SwlAPEsZnoBA\&ip\=186.64.170.207\&id\=o-ABPZs6OWUG5As-PKiP8zOYlHpaw_tgWzibECAz3fbn-F\&itag\=18\&source\=youtube\&requiressl\=yes\&mh\=yT\&mm\=31%2C29\&mn\=sn-j5caxupj5-nwvl%2Csn-hp57kn6e\&ms\=au%2Crdu\&mv\=m\&mvi\=1\&pcm2cms\=yes\&pl\=24\&initcwndbps\=1061250\&vprv\=1\&mime\=video%2Fmp4\&ns\=NYbtpqSjHZ0Zq4VyrJaAMksG\&gir\=yes\&clen\=52532427\&ratebypass\=yes\&dur\=840.608\&lmt\=1527732394812891\&mt\=1629319006\&fvip\=5\&fexp\=24001373%2C24007246\&c\=WEB\&n\=kcWjplwNR4gWJ6jpC\&sparams\=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt\&sig\=AOq0QJ8wRQIhAJyu2AqS5XWU-pRr6wcqSKO2_AqtDnkY-0z5wbKVZD5tAiByZW_kGjyMcHdaawIp5BP6YEhNDrr-HbO4i47MWqp-SA%3D%3D\&lsparams\=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps\&lsig\=AG3C_xAwRgIhAJkmZruHRKtnV82uZOFTlZZVYYc8DbfXNCDaNAXOqnbXAiEA-v2UEWz7HYdPv-Gugux8O63o_uXh8ZWWgFyBsKR2pIA%3D'
    triggers:
      - person_logging

  - id: "stream1"
    uri: 'https://r2---sn-j5caxupj5-nwvs.googlevideo.com/videoplayback?expire=1629342401&ei=YXYdYeW0MYTd4QSO076gAQ&ip=186.64.170.207&id=o-ANPmmLN4JDnEGy179KZ7cC8hnxnVznNILBG6me0e_DFX&itag=18&source=youtube&requiressl=yes&mh=Lt&mm=31%2C29&mn=sn-j5caxupj5-nwvs%2Csn-hp57kn6r&ms=au%2Crdu&mv=m&mvi=2&pl=24&initcwndbps=1097500&vprv=1&mime=video%2Fmp4&ns=crXqpvNJnS63fXSouQcmW7YG&gir=yes&clen=118955979&ratebypass=yes&dur=2048.580&lmt=1400852556579339&mt=1629320689&fvip=4&fexp=24001373%2C24007246&beids=23886210&c=WEB&n=6n4cDl7JKFstnZ6Vy&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgCDsJFR2xtUz1AeoPCZU8GLbKcU58VgjvaC0fEIdEjjcCIFOuX-i56RxLOBkQqI7Ye-rH7pAt5fR586ge1hCB1iYZ&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKpJFwXkVwBu76msXbmWZQrxp5XchbyflKVlyi70aRQJAiAX_cvY2Pqy5S8lF2jVVgAqK82y2MmEAujRMi2xnZc3DA%3D%3D'
    triggers:
      - person_logging

  - id: "stream2"
    uri: 'https://r2---sn-j5caxupj5-apge.googlevideo.com/videoplayback?expire=1629342855&ei=J3gdYbKeCIyqj-8PpYyv8AE&ip=186.64.170.207&id=o-AJi1RjPjykOzcjMr0IIK4CPnhxEYZGUuTYLrwZr4lhsb&itag=18&source=youtube&requiressl=yes&mh=LS&mm=31%2C29&mn=sn-j5caxupj5-apge%2Csn-hp57kn6s&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=24&initcwndbps=930000&vprv=1&mime=video%2Fmp4&ns=E57hC9b4cJGef4mNYBv0xS8G&gir=yes&clen=325747819&ratebypass=yes&dur=4741.050&lmt=1517088675279937&mt=1629320929&fvip=3&fexp=24001373%2C24007246&c=WEB&n=N-B6Xa0uEe0927sdy&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgCxJ_YS2O44UhvhGtC7etDTMUylRJk6_s2dTgBjr4zgcCIQCZk7QY8Y4t6ZMQk_6fnmBiLmcRazy286gHIPXESh-wHw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANL_0CKN8oskXWZNJn7YIJiBeR-92my6fsEUv3bMlQzJAiEAkrRyDhDiiePMPtydtpTOTKHIgoj8LxumXUovrNFUe1o%3D'
    triggers:
      - person_logging

  - id: "stream3"
    uri: 'https://r1---sn-j5caxupj5-nwve.googlevideo.com/videoplayback?expire=1629342907&ei=W3gdYYW3G82SkASaw7XgDw&ip=186.64.170.207&id=o-ACdhpYpdQxVHZ_otjZ0YSeyAoaW4UsDhK_Jz2jdjAf7A&itag=18&source=youtube&requiressl=yes&mh=jm&mm=31%2C29&mn=sn-j5caxupj5-nwve%2Csn-hp57knzz&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=1091250&vprv=1&mime=video%2Fmp4&ns=b8R7b8fmV1hZ7waJqSp-i7UG&gir=yes&clen=71863615&ratebypass=yes&dur=808.356&lmt=1597174835364166&mt=1629321167&fvip=6&fexp=24001373%2C24007246&c=WEB&txp=6216222&n=9-iZs_UXLy2JcR-Qj&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgJBTk_n4JiBXvH7TVbYnD2N167cZYG0LB0Q1BuQAZ4JcCIGWFNtPTkwpLrgHM8N-7-3gjH7tCGQGQrBNiHPjTv5cx&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJn__hGeAd6AveCBvK0tn1MSHxFmSKC_zWhny6vem3xTAiEAqCgEJsVj9ORHxfO12ky3IKn3WBuyoEGH657w0KKra_U%3D'
    triggers:
      - person_logging

filters:
  - name: person_filter
    labels:
      - male
      - child
    threshold: 0.7

  - name: animal_filter
    labels:
      - cat
      - dog
    threshold: 0.8

actions:
  - name: start_recording
    type: record_event
    length: 10
    location: /tmp/

  - name: log_event
    type: log_event
    location: /tmp/log.xls

triggers:
  - name: person_logging
    action: log_event
    filters:
      - person_filter
