model_params:
  disp_width: 320
  disp_height: 240
  model:
    detection: '/opt/model_zoo/TFL-OD-2000-ssd-mobV1-coco-mlperf-300x300/'

streams:
  - id: "stream0"
    uri: 'rtspt://170.93.143.139/rtplive/1701519c02510075004d823633235daa'
    triggers:
      - car_recording

  - id: "stream1"
    uri: 'rtspt://170.93.143.139/rtplive/1701519c02510075004d823633235daa'
    triggers:
      - car_recording

  - id: "stream2"
    uri: 'rtspt://170.93.143.139/rtplive/1701519c02510075004d823633235daa'
    triggers:
      - car_recording

  - id: "stream3"
    uri: 'rtspt://170.93.143.139/rtplive/1701519c02510075004d823633235daa'
    triggers:
      - car_recording

filters:
  - name: car_filter
    labels:
      - vehicle/car
    threshold: 0.5

  - name: animal_filter
    labels:
      - cat
      - dog
    threshold: 0.8

actions:
  - name: car_recording
    type: record_event
    length: 10
    location: /tmp/

  - name: log_event
    type: log_event
    location: /tmp/log.xls

triggers:
  - name: car_recording
    action: car_recording
    filters:
      - car_filter
