streams:
  - id: "stream0"
    uri: "rtsp://10.251.200.14:5000/stream"
    triggers:
      - person_logging

  - id: "stream1"
    uri: "rtsp://10.251.200.14:5000/stream"
    triggers:
      - person_logging

filters:
  - name: person_filter
    labels:
      - male
      - child
    threshold: 0.7

  - name: animal_filter
    labels:
      - cat
      - dog
    threshold: 0.8

actions:
  - name: start_recording
    type: record_event
    length: 10
    location: /tmp/

  - name: log_event
    type: log_event
    location: /tmp/log.xls

triggers:
  - name: person_logging
    action: log_event
    filters:
      - person_filter
